services:
  - type: web
    name: consumo-consciente-mvp
    env: static
    buildCommand: cd app && npm install && npm run build
    staticPublishPath: ./app/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin

